### ISSUE TITLE
Fetch project doesn't work (maybe new firmware 1.3)

### ISSUE THREAD

**Issue by andrestelex** [mzero/elk-herd-project#16]
It gets stuck there. Tried in Opera, Chrome and Brave, OSX 10.14
Digitakt using latest 1.3 firmware version
![image](https://user-images.githubusercontent.com/5502786/122559977-ecd39500-d037-11eb-8a97-0c0cad7e3286.png)

**Comment by jeatienzar** [comment]
Same for me. It gets stuck using Chrome. But I think you meant to say the new 1.30 firmware for Digitakt.

**Comment by mzero** [comment]
I think you mean 1.30 firmware? In any event, yes.... probably a simple fix (they may have bumped version numbers in there) - but I'll need to look into it early next week.

**Comment by andrestelex** [comment]
Yes, I meant 1.30. Thanks for the quick replies and help.

**Comment by jpkarvonen** [comment]
Chiming in to say this is occurring for me as well after the Digitakt's 1.30 firmware update. 

Thanks for such a great tool @mzero!

**Comment by alexboffey** [comment]
Just want to say, just discovered this project and amazing work!
Would be interested in seeing more source code or some API reference for the Digitakt which would have enabled this project! Maybe someone has some links they could share?

As other people have reported, I'm seeing the same behaviour for Digitakt 1.30 using Chrome 91.x on MacOS 10.15.x

**Comment by tslatts36** [comment]
> I think you mean 1.30 firmware? In any event, yes.... probably a simple fix (they may have bumped version numbers in there) - but I'll need to look into it early next week.

Hi there, 
just wondering if you've had any luck with fixing this bug? thanks in advanced!

**Comment by joaehun** [comment]
Managed to fetch the project with the beta version on the firmware 1.3 update but still havent done anything more with the program itself. 
Will put it to test now.

https://electric.kitchen/crunch/beta/elk-herd/

**Comment by mzero** [comment]
I think all reported issues with elk-herd and 1.30 have been resolved.  Waiting a few days to see if there are anymore and if not will move beta to release.
