### ISSUE TITLE
Fetch Project not working with Digitakt 1.50

### ISSUE THREAD

**Issue by tslatts36** [mzero/elk-herd-project#18]
Hey there, 

I noticed Fetching Project is not working with the new Digitakt 1.50 upgrade. It just gets stuck on the Fetching Project buffer bar. 

Just wondering if anyone else has had the same issue? Cheers. 
<img width="1245" alt="Screen Shot 2023-06-04 at 7 06 53 pm" src="https://github.com/mzero/elk-herd-project/assets/87414820/921135eb-2185-4539-93f8-1298b1255100">

**Comment by milkshakedoug** [comment]
Yup, I'm experiencing this as well. So to create an alert with no solve, just wanted to validate.

**Comment by gionvdb** [comment]
yes same issue here

**Comment by cplbertrand** [comment]
Hey,
Same here after updating to 1.50.

**Comment by surfacescan** [comment]
App looks amazing but the most critical feature for backing up my stuff is this Fetch Project and it doesn't work with 1.50 - would be amazing if @mzero you were able to take a quick look!  Thanks

**Comment by bartholomusic** [comment]
Same here, 1.50

**Comment by boocup** [comment]
ditto...cool project though

**Comment by bfunc** [comment]
+1 fetch project hangs and does nothing

**Comment by mzero** [comment]
OS 1.50 (and 1.51 and 1.51A) are now supported in the new beta.  See:

https://www.elektronauts.com/t/elk-herd-3-2-beta-for-digitakt-os-1-51a-and-earlier/184908
