### ISSUE TITLE
Is this project dead? Could it be open for contributions? 

### ISSUE THREAD

**Issue by zerubeus** [mzero/elk-herd-project#20]
See no updates for new OS 1.5 I would like to help if the project repo become open to contributions.

**Comment by TwilightOwl** [comment]
I hope the elektron team bought this code for further development and mzero signed up NDA. See no other reason why he keeps quite even at elektronauts for a long time but still visits the forum.

**Comment by zerubeus** [comment]
The only way, is to start a reverse engineering project for Overbrigde, I don't think Elektron are willing to provide any open API for Overbridre, this is the only way!

**Comment by ghosty141** [comment]
> The only way, is to start a reverse engineering project for Overbrigde, I don't think Elektron are willing to provide any open API for Overbridre, this is the only way!

Has anybody taken a look at that? I imagine unless they go out of their way by using encryption I believe it should be fairly straight forward to get a **VERY BASIC** upload of a single file for example working. But obviously heavily depends on how "nice" they are. I might take a look at it via wireshark and see how bad it is :D

**Comment by mzero** [comment]
1) The project isn't dead
2) I'm not dead
3) The code and project are still mine. 
4) The elektron team and I are in communication. There is no NDA, but then again, they aren't sharing seekret details with me.
5) I did start this project by reverse engineering... there was no deep attempt by elektron to obfuscate or encrypt anything.

**Comment by zerubeus** [comment]
Could you please share the process of how you found the midi messages for different actions? 🙏

**Comment by mzero** [comment]
Reverse engineering something like this isn't just a simple process I could
explain. And it took months and a lot of good guessing based on my
experience with these kinds of things.

- Mark
