### ISSUE TITLE
Nothing happens after sending project.

### ISSUE THREAD

**Issue by ghost** [mzero/elk-herd-project#9]
**Describe the bug**
I can fetch the project and make edits to the sample pool then when I click on send project the progress bar comes up in elk heard but nothing happens on the digitakt. 

**To Reproduce**
1. Fetch Project
2. Make edits to sample pool
3. Send project
4. Elk heard progress bar
5. No progress bar on digitakt
6. Changes aren't realised on digitakt

**Environment (please complete the following information):**
Digitakt 1.11

**Comment by mzero** [comment]
Are you on Linux by any chance?

**Comment by ghost** [comment]
The issue seemed to sort itself out the after a while, I'll close the thread.
